version: '3.8'
services:
  cassandra1:
    image: docker.io/bitnami/cassandra:latest
    hostname: cassandra1
    ports:
      - "7000:7000"
      - "9042:9042"
    volumes:
      - cassandra1_data:/bitnami
    networks:
      - cassandranet
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=nbd-cassa1ndra-cl1uste1r
      - CASSANDRA_DATACENTER = dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH-GossipingPropertyFileSnitch
      - CASSANDRA_USER = cassandra
      - CASSANDRA_PASSWORD=cassand r arpassword 
      - MAX_HEAP _SIZ'E=2G - HEAP _'NEWSIZE=200M
  cassandra2:
    image: docker.io/bitnami/cassandra:latest
    hostname: cassandra1
    ports:
      - "7001:7000"
      - "9043:9042"
    volumes:
      - cassandra_data_2:/bitnami
    networks:
      cassandranet:
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra2
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DATACENTER=dc1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - BITNAMI_DEBUG=1

volumes:
  cassandra_data_1:
  cassandra_data_2:
networks:
  cassandranet: { }
